### PR TITLE
Defining the recipes page as default

### LINKED ISSUE #79: Change default URL to recipes
When #68 is merged, we will need to:

- [x]  Change the default URL to recipes
- [x]  Add `@login_required` to recipes
- [x]  Remove `index.html` template and its URL and view method.

### PR DESCRIPTION
**Pull request by GilShechter**
### Description

This PR is changing the default route to the recipes page, and it will be valid only after successful login.
Close #79 

### What's new

- Removed the `index` template entirely
- Changes the route of `recipes` to `/`
- Updated the `test_recipes_view` to check the login requirement for an unauthorized user, then check redirection to the main page after a successful login
- Moved a fixture to the `conftest` file

### CODE REVIEW

**Comment by efraimvis** [comment]
If you take a look at the [DFD](https://github.com/redhat-beyond/tasties/blob/main/Tasties_DFD.png), we should have a landing page, leading out to a login page, leading out to a user homepage, and then finally the option to redirect to browse recipes. Since we have to stick to the DFD, and we don't have to present the entire website for the next demo - only one feature - Do we need this change at the moment?

**Comment by natifridman** [comment]
> If you take a look at the [DFD](https://github.com/redhat-beyond/tasties/blob/main/Tasties_DFD.png), we should have a landing page, leading out to a login page, leading out to a user homepage, and then finally the option to redirect to browse recipes. Since we have to stick to the DFD, and we don't have to present the entire website for the next demo - only one feature - Do we need this change at the moment?

You can always change the DFD with a PR if you think there is a need

**Comment by GilShechter** [comment]
We decided to adjust the DFD to this PR, so we can move forward with this one.

**Review by efraimvis — APPROVED** [review]

**Review by GalOved — APPROVED** [review]

**Review by natifridman — APPROVED** [review]
LGTM

**Pull request merged**
