### PR TITLE
Adding a Vagrantfile that responsible to bring up the VM

### LINKED ISSUE #3: fixed the PR https://github.com/redhat-beyond/beyond08-group1/pull/1
fixed the PR https://github.com/redhat-beyond/beyond08-group1/pull/1

### PR DESCRIPTION
**Pull request by GalOved**
closes #3 

Bringing up VM using Vagrantfile, based on the fedora/34-cloud-base

### CODE REVIEW

**Review by efraimvis — CHANGES_REQUESTED** [review]
I think you should include the port forwarding in the vagrantfile in this commit. It will save all of us some time, and make sure none of us miss it.

**Review by efraimvis — APPROVED** [review]

**Review by GilShechter — CHANGES_REQUESTED** [review]
I would suggest splitting your commit into two commits. One for the 'vagrantfile' and one for the '.gitignore' file.
Also, a new line is missing in '.gitignore' file.

**Review by GilShechter — APPROVED** [review]

**Review by natifridman — CHANGES_REQUESTED** [review]
Please add a meaningful commit message about this change

**Comment by GalOved** [comment]
@natifridman I change the commit now

**Comment by liornoy** [comment]
@GalOved can you please re-write the commit message,
as this commit doesn't bring up a VM but adds the Vagrantfile that is responsible for it.

**Comment by GalOved** [comment]
Hi @liornoy, I do the change.

**Review by natifridman — APPROVED** [review]
LGTM

**Pull request merged**
