### PR TITLE
Edit README.md file and added image

### LINKED ISSUE #16: Update README
@WaseemAbuSobe 
README file needs to be updated to reflect our project.

### PR DESCRIPTION
**Pull request by WaseemAbuSobe**
edite README.md 
Close #16

### CODE REVIEW

**Review by GilShechter — APPROVED** [review]
LGTM

**Review by GalOved — CHANGES_REQUESTED** [review]
The README and the logo looking good to me.
You still have in this PR the flake8, I think it is will make a conflict if the Flake8 PR (I'm not sure).
i suggest to remove the flake8 file.

**Review by efraimvis — CHANGES_REQUESTED** [review]
The flake8.yml file does not belong here, it's in a different PR. Please remove it.

**Review by GilShechter — APPROVED** [review]

**Comment by WaseemAbuSobe** [comment]
I delete the flake8 file and make squash.

**Comment by WaseemAbuSobe** [comment]
@ohadrevach  please make approve.

**Review by GilShechter — APPROVED** [review]

**Review by efraimvis — APPROVED** [review]

**Review by natifridman — APPROVED** [review]

**Pull request merged**
