### PR TITLE
Installing Django application

### LINKED ISSUE #7: Creating our Django application
Need to bootstrap the Django application once the environment is ready.

### PR DESCRIPTION
**Pull request by GilShechter**
Bootstrapping the Django application

- "tasties" folder with the python files was created
- "bootstrap.sh" modified to automate the environment

Closes #7

### CODE REVIEW

**Review by efraimvis — APPROVED** [review]
Looks good to me.

**Review by GalOved — APPROVED** [review]
look fine for me

**Review by ohadrevach — APPROVED** [review]
Looks fine for me

**Review by liornoy — APPROVED** [review]

**Comment by liornoy** [comment]
LGTM

**Pull request merged**
