### PR TITLE
Edited bootstrap.sh script to run data migrations

### LINKED ISSUE #52: Run migrations upon Vagrant up
We need to configure our Vagrant's bootstrap script to run our data migrations upon "vagrant up",
as per the [SOW](https://github.com/redhat-beyond/documents/blob/main/Beyond08-SOW.md#demo-1-november-13th-project-selection-and-setting-up-a-dev-environment:~:text=Your%20bootstrap%20script%20should%20run%20the%20data%20migrations%20when%20your%20Vagrant%20VM%20starts%20up)

### PR DESCRIPTION
**Pull request by efraimvis**
- Added code in bootstrap.sh to run migrations upon VM startup/provision, as per the SOW
- Closes #52

### CODE REVIEW

**Comment by GilShechter** [comment]
Isn't 'makemigration' command necessary here as well?

**Comment by efraimvis** [comment]
> Isn't 'makemigration' command necessary here as well?

I would strongly agree with that statement. However, please recall [this](https://github.com/redhat-beyond/tasties/pull/46#:~:text=Yes%2C%20you%20are%20correct%20this%20is%20part%20of%20the%20SOW%20I%20forgot...%20but%20you%20only%20need%20the%20migrate%20command%20as%20you%20already%20created%20the%20migration%20files%20so%20no%20need%20to%20run%20it%20every%20time%20the%20VM%20comes%20up) comment on one of your own PRs.

**Review by GilShechter — APPROVED** [review]

**Review by WaseemAbuSobe — APPROVED** [review]

**Review by ohadrevach — APPROVED** [review]
LGTM

**Review by GalOved — APPROVED** [review]
LGTM

**Comment by liornoy** [comment]
LGTM

**Review by liornoy — APPROVED** [review]

**Pull request merged**
