### PR TITLE
Proposing an ERD diagram for Django models

### LINKED ISSUE #23: Propose preliminary ERD diagram for Tasties

### PR DESCRIPTION
**Pull request by efraimvis**
- This is a proposed ERD diagram for Tasties, team and mentor input is requested.
- Closes #23

### CODE REVIEW

**Review by GalOved — CHANGES_REQUESTED** [review]
Good job. 
I recommend adding a line in the recipe table so that the recipe can track its ingredients and also the user can track their recpies.
This line would be interpreted as having a list of ingredirnts that all the recpises will keep.

**Comment by efraimvis** [comment]
@GalOved I see what you mean. I made some changes to the ERD in the manner you proposed, and also added a new 'Recipe-rating' table so we can keep track of every rating for a given recipe. I kept the old commit so we can keep track of the changes we make to the ERD.

**Comment by efraimvis** [comment]
Found a few problems with commit [Making changes to ERD proposal](https://github.com/redhat-beyond/tasties/pull/24/commits/7633125dc952645c24f0d696fb03941169eb54d9) - made a number of changes to address them, see commit message for [Removed some unnecessary changes](https://github.com/redhat-beyond/tasties/pull/24/commits/afbd7b1edc12e7926de123df15aa2bcf9d1769dc)

**Review by GalOved — APPROVED** [review]
The chagne look good to me. good job.

**Review by WaseemAbuSobe — DISMISSED** [review]
looking good

**Comment by liornoy** [comment]
Can you squash the commits please?

**Review by natifridman — COMMENTED** [review]
Some comments/questions:

**Recipe**
- You don't need to store ratings and the number of ratings, you have the `Rating` table for this. This can be a method in the recipe model.

**Recipe-x**
You don't need to use names such as `Recipe-comment`, you can just call it `Comment`.
You can take a look at this [project](https://github.com/redhat-beyond/ResuMe/tree/main/docs) where they did something similar

**User**
Please remember to use Django's built-in users table

**Ingredient-type**
Why do we need this table?

**Recipe-style**
Is this for recipe categories?

**Comment by liornoy** [comment]
I think it would be simpler to have only the recipe's description
as the place to describe the steps and ingredients.
This is because every recipe includes numerous steps and ingredients,
that are most likely different from other recipes' steps and ingredients,
and this could make the Ingredient and Steps databases huge.
and it would be much harder for debugging and developing in general.

**Comment by efraimvis** [comment]
> I think it would be simpler to have only the recipe's description as the place to describe the steps and ingredients. This is because every recipe includes numerous steps and ingredients, that are most likely different from other recipes' steps and ingredients, and this could make the Ingredient and Steps databases huge. and it would be much harder for debugging and developing in general.

@liornoy I see your point, and it could also save us effort when we build the recipe editing functionality; But if we do that, how would we go about searching recipes by ingredients? We want a functionality where we search recipes by a SET of ingredients, and we should get all the recipes that have an ingredient list with some intersection with this set we search by. The recipe's division into steps is mostly for end-user convenience (dividing the recipe in this manner provides a clear logical and visual flow to the recipe).

**Comment by liornoy** [comment]
First of all, I think that the "search recipes with a subset of ingredients" is an unusual functionality from a product perspective. I mean, you are free to disagree with me on that, but I've never asked the internet or a friend for a recipe that is based on some ingredients. It is more likely to look for recipes under a category like "Dairy" / "Italian" / "Gluten Free" - which the "recipe style" covers.

Also, it's complicated - How do you create objects in the ingredients table? does the user create them? if so, how do you avoid duplications caused by mis-spellings and variants? (water / cold water/ hot water/ glass of water/salt/spoon of salt/) this could get messier easily... 
Also when a user creates a recipe does he write all the descriptions with the instructions including the ingredients, and then he has to re-enter them again to a special check-box that is aligned with the ingredient database?

You could definitely implement that, but just be aware of all the stuff that needs to be taken into consideration. 

And regarding the Steps, you are missing a "steps" field under the recipe table - that points to all of the recipe's steps.

**Review by GalOved — DISMISSED** [review]
I think is represents the relationships in our project well, so for me it looking good.

**Review by natifridman — COMMENTED** [review]
**Recipe:**
- styles -> category
- Why do you need so many FK?
- Why do you need ingredients as part of a recipe?

**Ingredient**
Maybe we can change `original_unit_of_measurement` to `measturement_unit`?

**Comment by liornoy** [comment]
@efraimvis We can provide the same clarity from within the data model class. 
The names of the object's fields should describe the object, and not a logical operation we plan to do with it.

**Comment by efraimvis** [comment]
@natifridman @liornoy Thank you for your input. I've updated the PR, your concerns have been addressed.

**Review by natifridman — COMMENTED** [review]
One more question:
Since the relationship between `Recipe` and `Category` is many-to-many according to this ERD, how are you going to represent categories in the recipe?

**Comment by natifridman** [comment]
Thanks for the clarification.
>  If you're asking specifically about the ERD - how are we going to keep track of Categories associated with a Recipe - then there's a "categories" row in Recipe which has Category's "id" row as a FK.

But `categories` in the ERD is int, which as I understand is the category ID, so how are you going to store more than one per recipe? The recipe is going to be stored a couple of times in the table with different categories?

**Comment by efraimvis** [comment]
> But `categories` in the ERD is int, which as I understand is the category ID, so how are you going to store more than one per recipe? The recipe is going to be stored a couple of times in the table with different categories?

@natifridman I've done some research and I'm now aware that a many-to-many relationship between tables will usually be expressed by adding a "join table" (or "junction table"). Since we're seeing [here](https://docs.djangoproject.com/en/4.1/topics/db/examples/many_to_many/) that it will be, in fact, unnecessary for us to create a new "Recipe-Categories" model to get the functionality we want - it is my opinion that we may leave the current arrangement as-is, and regard what we have in the ERD right now as a form of shorthand.

**Review by natifridman — APPROVED** [review]

**Review by WaseemAbuSobe — APPROVED** [review]
look very good

**Review by GalOved — APPROVED** [review]
Looking good to me.

**Pull request merged**
