### PR TITLE
Adding DFD

### LINKED ISSUE #25: Propose DFD for Tasties

### PR DESCRIPTION
**Pull request by GalOved**
Adding DFD that show the flow between users to recipe view page.
Close #25

### CODE REVIEW

**Review by WaseemAbuSobe — DISMISSED** [review]
looking good

**Review by efraimvis — APPROVED** [review]
Looks comprehensive enough. There are some arrows that I think may be redundant - from "Rating" data store to "View Recipe" for example (doesn't "View Recipe" already have all the ratings it needs to display through the recipe which it gets from "Browse Recipes"?). I would like to discuss this point of redundant arrows.

**Review by WaseemAbuSobe — DISMISSED** [review]
look very nice

**Comment by GalOved** [comment]
@efraimvis, You are right in that browse recipe updates the view recipe with everything, but after a change in the add rating or add comment process, for example, in my opinion, the view recipe needs to be updated again with the changes that happened, so I sent an arrow from the comment database that updates the process of recipe view.

**Review by ohadrevach — APPROVED** [review]
LGTM

**Review by efraimvis — APPROVED** [review]
> @efraimvis, You are right in that browse recipe updates the view recipe with everything, but after a change in the add rating or add comment process, for example, in my opinion, the view recipe needs to be updated again with the changes that happened, so I sent an arrow from the comment database that updates the process of recipe view.

I see that point of view. Very well, I don't think this changes anything with what we want to describe. I approve.

**Review by natifridman — APPROVED** [review]

**Pull request merged**
