### PR TITLE
Creating conftest.py and modified Category and Ingredient tests

### LINKED ISSUE #66: Create conftest.py
Create conftest .py for  fixtures  required for the tests.

### PR DESCRIPTION
**Pull request by ohadrevach**
Creating conftest.py file and moved the fixtures there,
modified Category and Ingredient tests that will work  with new migrations.

closes #66

### CODE REVIEW

**Review by efraimvis — APPROVED** [review]
Thanks, LGTM.

**Review by GilShechter — COMMENTED** [review]
LGTM

**Review by natifridman — APPROVED** [review]
LGTM, nice work!

**Review by GalOved — DISMISSED** [review]
LGTM

**Review by efraimvis — DISMISSED** [review]

**Review by natifridman — APPROVED** [review]
Approved, please squash your commits.
For some reason, looks like you use 2 different Github users for your commits

**Review by GilShechter — APPROVED** [review]

**Review by WaseemAbuSobe — APPROVED** [review]
LGTM

**Review by GalOved — APPROVED** [review]
Looking good, good work

**Review by natifridman — APPROVED** [review]
@ohadrevach Please add a comment after you resolve issues so we'll know you did it.
You can also change the label

**Pull request merged**
