### PR TITLE
Add flake8 workflow for automatic CI test

### LINKED ISSUE #17: Add flake8 workflow for automatic CI testing
@WaseemAbuSobe 
A flake8 workflow needs to be added to the project.

### PR DESCRIPTION
**Pull request by WaseemAbuSobe**
added flake8.yml file and image
Close #17

### CODE REVIEW

**Review by GalOved — CHANGES_REQUESTED** [review]
The flake8 file look good for me.
I think you suold add the image to the README PR.

**Review by GilShechter — APPROVED** [review]
LGTM

**Review by ohadrevach — APPROVED** [review]
LGTM

**Review by efraimvis — APPROVED** [review]
LGTM

**Comment by natifridman** [comment]
Please change the PR title to something meaningful

**Comment by WaseemAbuSobe** [comment]
now the title good ? @natifridman

**Review by natifridman — APPROVED** [review]

**Pull request merged**
